# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'AutoLayout01' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'SnapKit'

  # Pods for AutoLayout01

end
