# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Rx_todo_list' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Rx_todo_list

  pod 'RxSwift'
  pod 'RxCocoa'
end
