# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'crud_firebase' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
	
  # Pods for crud_firebase
pod 'Firebase/Auth'
pod 'Firebase/Firestore'
# add pods for desired Firebase products
# https://firebase.google.com/docs/ios/setup#available-pods 

 target 'crud_firebaseTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'crud_firebaseUITests' do
    # Pods for testing
  end

end
